[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=fedora
Release=41

[Content]
Packages=
    kernel
    selinux-policy-targeted
    systemd
    systemd-boot-unsigned
    systemd-networkd
    systemd-resolved
    systemd-journal-remote
    jq
    xxd
    python3
KernelCommandLine="selinux=0"
