[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe
RepositoryKeyFetch=yes

[Content]
Packages=
	linux-image-virtual
	systemd
	systemd-boot-efi
	systemd-resolved
	plymouth
	login.defs
	login
	systemd-journal-remote
	openssl
	ca-certificates
	jq
	xxd
	python3

# Remove all guest kernel modules to optimize the guest image size
KernelModulesExclude=.*

# Add required guest kernel modules
KernelModulesInclude=
	msr
	sev-guest

	# Core networking support on the guest
	net/core/
	net/ipv4/
	net/ipv6/
	net/packet/
	net/netfilter/

	# virtio-net-pci related  network modules
	drivers/net/virtio_net.ko
	drivers/virtio/virtio.ko
	drivers/virtio/virtio_ring.ko
	drivers/virtio/virtio_pci.ko

	# vsock support for host-guest communication
	net/vmw_vsock/

[Build]
Environment=VERSION="26.04"
