[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=opensuse
Release=16.0
RepositoryKeyFetch=yes

[Content]
Packages=
        kernel-default
        systemd
        systemd-boot
        systemd-networkd
        systemd-resolved
        systemd-journal-remote
        zypper
        udev
        iputils
        ca-certificates
        p11-kit-tools
        jq
        patterns-devel-base-devel_basis
        bind-utils
        xxd
        python3

[Build]
Environment=VERSION="16.0"
