[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=ubuntu
Release=questing
Repositories=universe

[Content]
Packages=
	linux-image-virtual
	systemd
	systemd-boot-efi
	systemd-resolved
	plymouth
    login.defs
	login
    systemd-journal-remote
    openssl
    ca-certificates
    jq
	xxd
	python3

[Build]
Environment=VERSION="25.10"
