[Include]
Include=../../modules/build/host

[Distribution]
Distribution=fedora
Release=44

[Content]
Packages=
    kernel
    selinux-policy-targeted
    systemd
    systemd-boot-unsigned
    systemd-networkd
    systemd-resolved
    qemu-kvm-core
    edk2-ovmf
    dnf
    systemd-journal-remote
    net-tools
    openssh-server
    xxd
    python3
    python3-devel
    python3-pip
    python3-emoji
    jq
    avahi
    g++
KernelCommandLine="selinux=0"

[Build]
Environment=VERSION="44"
